club:
  name: "The Ultra Syndicate"

report:
  start_date: "2026-09-28"
  output_directory: "reports"

sync:
  hour: 21
  activity_limit: 100

activities:
  include:
    - Run
    - TrailRun

dashboard:
  recent_activities: 20
