apps:

  app1:
    athletes:
      - Chirag
      - Vivek
      - Ralph
      - Vijay
      - Abhilash
      - Vinukumar
      - Sukesh
      - Sourabh
      - Sarangi
      - Maran

  app2:
    athletes: []